"""
this module is created for for loop in python. for loop is used to iterate over a sequence (list, tuple, string) or other iterable objects. it is used to execute a block of code repeatedly for a fixed number of times. the syntax of for loop is:
for variable in sequence:
    # code to execute for each element in the sequence
"""


sem_wise_percentage = [85.5, 90.0, 92.5, 88.0, 91.0]

for percentage in sem_wise_percentage:
    print(f"Semester percentage: {percentage}%")
    
    
# for loop with string
name = "Python Programming"
for char in name:
    print(char)
    
#  for loop with tuple
fruits = ("apple", "banana", "cherry")
for fruit in fruits:
    print(fruit)
    
# for loop with dictionary
student_marks = {"Alice": 85, "Bob": 90, "Charlie": 92}

# To print only the keys by using for loop from the dictionary
for student in student_marks:
    print(student)

# Printing key and value of the dictionary by using for loop from the dictionary
for student in student_marks:
    print(f"{student}: {student_marks[student]}")
    
# Printing both keys and values by using for loop from the dictionary and items() method usage to do it in a more efficient
# way
# It will convert the dictionary into a tuple of key-value pairs and then we can unpack the tuple into two variables
# (student and marks) in the for loop
for i in student_marks.items():
    print(i)
    print(f"key : {i[0]}, value: {i[1]}")

# Unpacking the tuple of key-value pairs into two variables (student and marks) in the for loop
for student, marks in student_marks.items():
    print(f"{student}: {marks}")
    
# for loop with range() function
# syntax is:
# for variable in range(start, stop, step):
# start is the starting value of the sequence (default is 0)
# stop is the ending value of the sequence (exclusive)
# step is the increment value of the sequence (default is 1)
# range() - built-in function in python that generates a sequence of numbers based on the specified start, stop,
# and step values. it is commonly used in for loops to iterate a specific number of times or to generate 
# a sequence of numbers for various purposes.
# It's syntax is similar to slicing syntax in python, but it generates a sequence of numbers instead of slicing a sequence.
# range() function can take one, two, or three arguments:
# 1. range(stop): generates a sequence of numbers from 0 to stop-1 with a step of 1.
# 2. range(start, stop): generates a sequence of numbers from start to stop-1 with a step of 1.
# 3. range(start, stop, step): generates a sequence of numbers from start to stop-1 with a step of step.


# Range method with start stop and step arguments.
# for i in range (start, stop, step): - stop is not included in the sequence generated by the range() function, 
# it generates numbers up to stop-1.
#     # code to execute for each value of i in the range
for i in range(1, 10, 1):
    print(i)
    
# altering the steps - generating the even numbers from 0 to 20 by using range() function with step argument as 2
for i in range(0, 20, 2):
    print(i)
    
# printing the reverse order of numbers from 10 to 1 by using range() function with step argument as -1
for i in range(10, 0, -1):
    print(i)
    
# range(start, stop) - generates a sequence of numbers from start to stop-1 with a step of 1.
for i in range(1, 10):
    print(i)
    
# range(stop) - generates a sequence of numbers from 0 to stop-1 with a step of 1.
for i in range(10):
    print(i)

# for loop to have collection value in variable. 
groceries = ["milk", "bread", "eggs", "fruits", "vegetables"]
for item in groceries:
    print(item)

# for loop with index and value using enumerate() function. enumerate() function is used to get the index and value of the elements in a sequence. it returns an enumerate object which is an iterator that produces pairs of index and value for each element in the sequence. the syntax of enumerate() function is:
# enumerate(sequence, start=0)
groceries = ["milk", "bread", "eggs", "fruits", "vegetables"]
for i in range(len(groceries)):
    print(f"{i}. {groceries[i]}")
    
